<?php
/**
 * Implements hook_form_alter().
 */
function bps_core_form_alter(&$form, &$form_state, $form_id) {
 dpm($form_id);
 if ($form_id == 'ordenes_node_form') {
   $module_path = drupal_get_path('module', 'bps_core');
   drupal_add_css($module_path . '/css/bps_core.css');
 }
 if ($form_id == 'cotizaciones_node_form') {
   $size = count($form['field_referencias']['und']);
   $module_path = drupal_get_path('module', 'bps_core');
   drupal_add_js($module_path . '/js/bps_core.js');
   drupal_add_css($module_path . '/css/bps_core.css');
   foreach ($form['field_referencias']['und'] as $key => $value) {
     if (is_numeric($key)) {
       $form['field_referencias']['und'][$key]['field_porcentaje_impuesto']['und'][0]['value']['#size']=3;
       $form['field_referencias']['und'][$key]['field_porcentaje_impuesto']['und'][0]['value']['#attributes']= array('class'=>array('porcentaje_impuesto'));
       $form['field_referencias']['und'][$key]['field_descuento']['und'][0]['value']['#size']=3;
       $form['field_referencias']['und'][$key]['field_descuento']['und'][0]['value']['#attributes']= array('class'=>array('descuento'));
       $form['field_referencias']['und'][$key]['field_ref_cantidad']['und'][0]['value']['#size']=4;
       $form['field_referencias']['und'][$key]['field_ref_cantidad']['und'][0]['value']['#attributes']= array('class'=>array('cantidad'));
       $form['field_referencias']['und'][$key]['field_valor_unitario']['und'][0]['value']['#size']=9;
       $form['field_referencias']['und'][$key]['field_valor_unitario']['und'][0]['value']['#attributes']= array('class'=>array('valor_unitario'));
       $form['field_referencias']['und'][$key]['field_valor_iva']['und'][0]['value']['#attributes'] = array('readonly'=>array('true'));
       $form['field_referencias']['und'][$key]['field_total']['und'][0]['value']['#attributes'] = array('readonly'=>array('true'));
     } 
   }
   $form['total_cotizacion'] = array(
    '#type' => 'fieldset',
    '#title' => 'Totales',
    '#disabled' => TRUE,
    '#size' => 9,
    '#weight' => 4.5,
    '#attributes' => array('class'=>array('fliedset_totales')), 
   );

   $form['total_cotizacion']['subtotal'] = array(
    '#type' => 'textfield',
    '#title' => 'Subtotal',
    '#disabled' => TRUE,
    '#size' => 9,
    '#weight' => 5,
    '#attributes' => array('class'=>array('totales')), 
   );
   $form['total_cotizacion']['descuentos'] = array(
    '#type' => 'textfield',
    '#title' => 'Descuentos',
    '#disabled' => TRUE,
    '#size' => 9,
    '#weight' => 5,
    '#attributes' => array('class'=>array('totales')), 
   );
   $form['total_cotizacion']['total_iva'] = array(
    '#type' => 'textfield',
    '#title' => 'Iva',
    '#disabled' => TRUE,
    '#size' => 9,
    '#weight' => 5,
    '#attributes' => array('class'=>array('totales')), 
   );
   $form['total_cotizacion']['total_cotizacion'] = array(
    '#type' => 'textfield',
    '#title' => 'Total',
    '#disabled' => TRUE,
    '#size' => 9,
    '#weight' => 5,
    '#attributes' => array('class'=>array('totales')), 
   );
 }
 if ($form_id == 'field-collection-item-form'){
   $form['field_ref_cantidad']['und'][0]['value'] = array('class'=>array('cantidad'));
 }

 if ($form_id == 'erpal_contact_node_form') {
   $form['#validate'][] = '_validate_custom_contact';
 }


}
/**
 * Function validate id unique
 */ 
function _validate_custom_contact($form, &$form_state) {
  $values = $form_state['values'];
  dpm($values['field_documento_identidad']);
  if (isset($values['field_documento_identidad']['und'][0]['value']) && !empty($values['field_documento_identidad']['und'][0]['value'])){
    $query = db_select('field_data_field_documento_identidad', 'i');
    $query->addField('i','entity_id','nid');
    $query->condition('i','field_documento_identidad_value',$values['field_documento_identidad']['und'][0]['value']);
    $result = $query->execute()->fetchObject();
    if (isset($result->nid) && !empty($result->nid) && is_numeric($result->nid) && $result->nid > 0) {
      form_set_error('field_documento_identidad', 'El documento de identidad ya existe en la base de datos');
    }
  }
}